en = {

    "button":{
        "exit":"Exit",
        "suivant":"following",
        "precedant":"previous"
    },
    "regle": {
        "txt_regle1": 'Rules of "The Survivor":',
        "regle1_2":'"The Survivor" is a 2D platformer in which you play the main character, Eden.',
        "regle1_3":"I have been walking for days in the hope of finally reaching the end of this journey...",
        "regle1_4":"Each day is a little longer than the last, but they seem to repeat themselves endlessly...",
        "regle1_5":"Survival capsules are becoming scarce, the living are becoming absent and the survivors",
        "regle1_6":"are no longer...The factory must not be far away... With the sun as my only ",
        "regle1_7":"reference point, I no longer have any notion oftime, but I know where I am going! ",
        "regle1_8":"The danger is creeping up on me more and more every day, but restarting the is all that ",
        "regle1_9":"matters... Since the night of the dark lightning 60 moons ago,no more capsules come out... ",
        "regle1_10":"And the frolicking shadows that are becoming more and moremany, are surely not to blame... ",
        "regle1_11":"If I do nothing, we are doomed...The capsules on my path are the last existing ones,  ",
        "regle1_12":"the last ramparts of humanity...For years, man pushed the land to the limit.",
        "regle1_13":"As a result of pollution and intensive destruction, resources were becoming scarce,",
        "regle1_14":"and with them disappeared the little biodiversity that had managed to survive until now...",
        "regle1_15":"As we have always done, we have overestimated ourselves and sunk",
        "regle1_16":"the earth in an era of chaos... The creation of these capsules was a blessing!",
        "regle1_17":"No side effects, no pollution, no waste of resources! An oasis in the middle of the desert...",
        "regle2_2":"Water, nutrients and oxygen, these capsules were our only hope... but after a distribution",
        "regle2_3":"and worldwide consumption, the first ravages appeared...",
        "regle2_4":"the population was struck down by these capsules, from which only a tiny fraction of the",
        "regle2_5":"population was imunised... These imumunized were then the survivors, guarantors of the future",
        "regle2_6":"of humanity...This first generation was my parents' generation...",
        "regle2_7":"But the lack of capsules in recent times has decimated almost all the survivors...",
        "regle2_8":"I am forced to venture out of the shelter alone, with only hope,",
        "regle2_9":"this mysterious factory...",
        "regle3_1":"The game controls are as follows:",
        "espace":"Jump",
        "t1":"Running to",
        "t1bis":"the left",
        "t2":"Running to",
        "t2bis":"the right",
        "t3":"Opening a box",
        "regle4_1":"The game's interactions are as follows:",
        "regle4_2":"During the game, your life goes down.",
        "regle4_3":"continuously. It regenerates when",
        "regle4_4":" you catch the life capsules.",
        "regle4_5":"On your way, you will come across the",
        "regle4_6":"black walkers. It appears the",
        "regle4_7":"Most of the time, they emerge from the ground.",
        "regle4_8":"Try to avoid them, their",
        "regle4_9":"attacks can be deadly.",
        "regle4_10":"And beware of traps.",
        "regle4_11":"You can also come across chests, which will allow you to,",
        "regle4_12":"randomly, to acquire bonuses or malus ",
        "regle4_13":"They may contain : ",
        "regle4_14":"A super planet",
        "regle4_15":"A syringe",
        "regle4_16":"A ruby",
        "regle4_17":"Regenerates the entire ",
        "regle4_18":"life gauge",
        "regle4_19":"Multiply or divide by 3",
        "regle4_20":"the life contribution of the capsules",
        "regle4_21":"Regenerates up to",
        "regle4_22":"half of the gauge",
    },
    "menu": {
        "Regle": 'Rules',
        "Start": 'Start',
        "Option": 'Options',
        "Credits": 'Credits',
        "Facile": "Easy",
        "Moyen": "Medium",
        "Difficile": "Hard",
        "Son": 'Sounds',
        "Music": "Music",
        "Commandes":"Directional keys",
        "Indisponible":"Difficulty's choice not available",
        "Score1":"High score from : ",
        "Score2":"The record is set at ",
        "Score3":"This was established on ",
        "Score4":" in a session of ",
        "Score5":" attempts",
        "Score6":"  minutes and ",
        "Score7":"  seconds in ",
        "Score8":" mode"
    },
    "credit": {
        "credits1": "An original creation by Yiwen Jiang and Dujarrier-Lesueur Raphaël",
        "credits2": "Introducing music: Goetia - Dark Magic Music",
        "credits3": "Game music: Myuu - Misconception",
        "credits4": "Introduction and game background: archive.nyafuu.org and 3D Academy",
        "credits5": "Characters and sprites : Google image ",
        "credits6": "final factory image: Jordy Meow ",
        "credits7": "Bruitages : sound-fishing & soundbible",
        "credits8":"Background used for languages choices: 'Night city' from Pinterest"
    },
    "gameover": {
        "GO": "Game Over !",
        "com": "You failed to save the Earth",
        "retour": 'Back to the menu',
        "rejouer": 'Play again'
    },
    "putpause": {
        "Reprendre": 'Take over',
        "Recommencer": 'Start again',
        "Retour_menu2": 'Back to the menu'
    },
    "win": {
        "menu":"return to menu",
        "Rejouer2":"Play again",
        "win": "Well done!",
        "win1": "Thanks to your bravery, ",
        "win2": "you allowed Eden to arrive",
        "win3": "at the end breast and safe !",
        "win4": "Once past the black walkers,",
        "win5": "the factory has been relaunched,",
        "win6": "which had the effect of eradicating ",
        "win7": "the Black Walkers, thus saving",
        "win8": "the last survivors of the Earth",
        "win9":"NEW RECORD ! ENTER YOUR NAME",
        "win10":"Press 'enter' to validate the name",
        "win11":"CLICK and ENTER a name",
        "win12":"MAXIMUM NAME SIZE REACHED"
        
    },
    "draw":{
            "jauge":"Attention low gauge!"
    },
    "dialoge":{
            "d_b1":"You must be",
            "d_b1bis":"a survivor...",
            "d_b2":"If I can help you ",
            "d_b2bis":"give advice...",
            "d_b3":"Be aware of",
            "d_b3bis":"black walkers..."
    }
}