fr = {

    "button":{
        "exit":"Sortie",
        "suivant":"suivant",
        "precedant":"précédent"
    },
    "regle":{
        "txt_regle1":'Règles de "The Survivor":',
        "regle1_2":'"The survivor" est un platformer 2D dans lequel vous incarnez le personnage principal, Eden.',
        "regle1_3":"Je marche, depuis des jours durant, dans l'espoir d'arriver finalement au bout de ce périple...",
        "regle1_4":"Chaque jour est un peu plus long que le précédent, mais ils semblent se répéter inlassablement...",
        "regle1_5":"Les capsules de survie se font rare, le vivant se fait absent et les survivants ne sont plus...",
        "regle1_6":"La fabrique ne doit plus être loin... Avec le soleil comme seul repère, je n'ai plus de notion de",
        "regle1_7":"temps, mais je sais où je vais ! Le danger me guète chaque jour un peu plus, mais relancer la",
        "regle1_8":"fabrique est tout ce qui compte... Depuis la nuit aux éclairs sombres, il y a de cela 60 lunes,",
        "regle1_9":"plus aucune capsule n'en sort... Et les ombres batifolantes qui se font de plus en plus",
        "regle1_10":"nombreuses, n'y sont sûrement pas pour rien... Si je ne fais rien, nous sommes condamnés...",
        "regle1_11":"Les capsules sur mon chemin sont les dernières existantes, les derniers remparts de l'humanité... ",
        "regle1_12":"Des années durant, l'homme poussa la terre jusque dans ses derniers retranchements.",
        "regle1_13":"A coup de pollution et de destruction intensive, les ressources se faisaient alors rares,",
        "regle1_14":"et disparaissaient avec elles, le peu de biodiversité qui était parvenu à tenir jusque ici...",
        "regle1_15":"Comme nous l'avons toujours fait, nous nous sommes surestimés et nous avons fait sombrer",
        "regle1_16":"la terre dans une ère de chaos... La création de ces capsules fut alors une bénédiction !",
        "regle1_17":"Sans effets secondaires, sans pollution, ni gaspillage de ressources ! Un oasis au millieu du désert...",
        "regle2_2":"Eau, nutriments et oxygène, ces capsules étaient notre seul espoir... mais après une distribution",
        "regle2_3":"et une consommation d'envergure mondiale, les premiers ravages apparurent...",
        "regle2_4":"la population fut terrassée par ces capsules, desquelles seule une infime partie de la",
        "regle2_5":"population était imunisée... Ces imumunisés étaient alors les survivants, garant de l'avenir",
        "regle2_6":"de l'humanité...Cette première génération fut celle de mes parents...",
        "regle2_7":"Mais le manque de capsules ces derniers temps a décimé casi totalité des survivants...",
        "regle2_8":"Je suis contraint de m'aventurer seul hors du refuge, avec pour seul espoir,",
        "regle2_9":"cette mystérieuse fabrique...",
        "regle3_1":"Les contrôles du jeu sont les suivants :",
        "espace":"Sauter",
        "t1":"Courir vers",
        "t1bis":"la gauche",
        "t2":"Courir vers",
        "t2bis":"la droite",
        "t3":"Ouvrir un coffre",
        "regle4_1":"Les interactions du jeu sont les suivantes :",
        "regle4_2":"Durant la partie, votre vie descend.",
        "regle4_3":"continuellement. Elle se régénère lorsque",
        "regle4_4":" vous attrapez les capsules de vie.",
        "regle4_5":"Sur votre chemin, vous croiserez les ",
        "regle4_6":"marcheurs noirs. Il apparaissent la",
        "regle4_7":"plupart du temps en sortant du sol.",
        "regle4_8":"Essayez de les éviter, leurs",
        "regle4_9":"attaques peuvent être mortelles.",
        "regle4_10":"Et prenez garde aux pièges !.",
        "regle4_11":"Vous pourrez également croiser des coffres, qui vous permettront,",
        "regle4_12":"au hasard, d'acquérir des bonus ou des malus ",
        "regle4_13":"Ils peuvent contenir : ",
        "regle4_14":"Une super planète",
        "regle4_15":"Une seringue",
        "regle4_16":"Un rubis",
        "regle4_17":"Régénère toute la ",
        "regle4_18":"jauge de vie",
        "regle4_19":"Multiplie ou divise par 3",
        "regle4_20":"l'apport en vie des capsules",
        "regle4_21":"Régénère jusqu'à la",
        "regle4_22":"moitié de la jauge",
    },
    "menu":{
        "Regle":'Règles',
        "Start":'Start',
        "Option":'Options',
        "Credits":'Crédits',
        "Facile":"Facile",
        "Moyen":"Moyen",
        "Difficile":"Difficile",
        "Son":'Sons',
        "Music":"Musiques",
        "Commandes":"Touches directionnelles",
        "Indisponible":"Choix de la difficulté indisponible",
        "Score1":"Meilleur score de : ",
        "Score2":"Le record est établi à ",
        "Score3":"Celui-ci à été établi le ",
        "Score4":" sur une session de ",
        "Score5":" tentatives",
        "Score6":"  minutes et ",
        "Score7":"  secondes en mode ",
        "Score8":"",

    },
    "credit":{
        "credits1":"Une création originale de Yiwen Jiang et Dujarrier-Lesueur Raphaël",
        "credits2":"Music d'introduction: Goetia - Dark Magic Music",
        "credits3":"Music de jeu: Myuu - Misconception",
        "credits4":"Fond d'écran introductif et en jeu: archive.nyafuu.org and 3D Academy ",
        "credits5":"Personnages et sprites : Google image ",
        "credits6":"image de l'usine finale: Jordy Meow ",
        "credits7":"Bruitages : sound-fishing & soundbible",
        "credits8":"Fond d'écran choix des langues : 'Ville nuit' de Pinterest"
    },
    "gameover":{
        "GO":"Game Over !",
        "com":"Vous n'avez pas réussi à sauver la Terre",
        "retour":'Retour au menu',
        "rejouer":'Rejouer'
    },
    "putpause":{
        "Reprendre":'Reprendre',
        "Recommencer":'Recommencer',
        "Retour_menu2":'Retour au menu'
    },
    "win":{
        "menu":"retourner au menu",
        "Rejouer2":"Rejouer",
        "win":"Bravo !",
        "win1":"Grâce à votre bravoure, ",
        "win2":"vous avez permis à Eden d'arriver",
        "win3":"au bout sein et sauf !",
        "win4":"Une fois passé les marcheurs noirs,",
        "win5":"la fabrique à été relancée,",
        "win6":"ce qui eu pour effet d'éradiquer ",
        "win7":"les marcheurs noirs, sauvant ainsi",
        "win8": "les derniers survivants sur terre",
        "win9":"NOUVEAU RECORD ! SAISISSEZ VOTRE NOM",
        "win10":"Appuyez sur 'entrer' pour valider le nom",
        "win11":"CLIQUER puis SAISIR un nom",
        "win12":"TAILLE MAXIMUM DU NOM ATTEINT"
    },
    "draw":{
        "jauge":"Attention jauge faible !"
    },
    "dialoge":{
        "d_b1":"Vous devez être",
        "d_b1bis":"un survivant...",
        "d_b2":"Si je peux vous ",
        "d_b2bis":"donner un conseil...",
        "d_b3":"Prenez garde aux ",
        "d_b3bis":"marcheurs noirs..."
    }

}